#Server Port: Your application runs locally on port 8080.
server.port=8080

#Database Target: The database is named test and runs completely in-memory. It wipes clean every time the application shuts down.
spring.datasource.url=jdbc:h2:mem:test

#Database as a Local File
# spring.datasource.url=jdbc:h2:file:./data/test

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#Schema Management: The create-drop strategy creates your tables at startup and drops them when the application terminates.
spring.jpa.hibernate.ddl-auto=create-drop

#Web Interface Console: You can access the H2 Database Web Interface by running your app and opening http://localhost:8080/h2-console in your browser.
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
